version: "3.9"
services:
  backend:
    image: afworkspace:1.0
    volumes:
      - /var/data/AF-workspace/client/build/:/app/public
      - /var/data/uploads/:/app/shared_files
    restart: on-failure
    command: >
      bash -c "node src/index.js"
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ORIGIN=https://afworkspace.fkor.us;http://localhost:3000
